language: php
 - 5.5.9
 - 7.0

install:
 - cd ./projects/tests/
 - composer install

script:
 - cd ./projects/tests/
 - output_runall=`php ./run_all.php`
 - output_runallfolders=`php ./run_all_folders.php`
 - output_runexcludefiles=`php ./run_exclude_files.php`
 - if [ "$output_runall" != "" ] || [ "$output_runallfolders" != ""  ] || [ "$output_runexcludefiles" != "" ] 
 - then
 - echo "progpilot tests failed"
 - fi
