language: php
 - 7.0.7

install:
 - cd ./projects/tests/
 - rm -f composer.lock
 - if [ -d "vendor" ]; then
 - rm -rf vendor/*
 - rmdir vendor/
 - fi
 - composer clearcache
 - composer install

script:
- |
 output_runall=`php ./run_all.php`
 output_runallfolders=`php ./run_all_folders.php`
 output_runexcludefiles=`php ./run_exclude_files.php`
 
 if [ "$output_runall" != "" ] || [ "$output_runallfolders" != ""  ] || [ "$output_runexcludefiles" != "" ]; then
  echo "$output_runall,$output_runallfolders,$output_runexcludefiles";
  exit 1;
 else
  exit 0;
 fi;
