language: php
php:
 - '7.0'
 - '7.1'
 - '7.2'
 
before_install:
 - sudo apt-get update
 - sudo apt-get install g++ cpp libxml2-dev build-essential curl git python libglib2.0-dev patchelf -y
 - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
 - export PATH=`pwd`/depot_tools:"$PATH"
 - fetch v8
 - cd v8
 - git checkout 6.4.388.18
 - gclient sync
 - tools/dev/v8gen.py -vv x64.release -- is_component_build=true
 - ninja -C out.gn/x64.release/
 - sudo mkdir -p /opt/v8/{lib,include}
 - sudo cp out.gn/x64.release/lib*.so out.gn/x64.release/*_blob.bin out.gn/x64.release/icudtl.dat /opt/v8/lib/
 - sudo cp -R include/* /opt/v8/include/
 - for A in /opt/v8/lib/*.so; do sudo patchelf --set-rpath '$ORIGIN' $A; done
 - printf "\n" | pecl install v8js-2.1.0
 - phpenv config-add travis.php.ini
 - travis_retry composer self-update

install:
 - cd ./projects/tests/
 - rm -f composer.lock
 - rm -rf vendor/
 - composer clearcache
 - composer install

script:
 - ./vendor/bin/phpunit
