language: php
php:
 - '7.0'
 - '7.1'
 - '7.2'
 
before_install:
 - sudo apt-get update
 - sudo apt-get install libv8-dev g++ cpp libxml2-dev -y
 - printf "\n" | pecl install v8js-2.1.0
 - phpenv config-add travis.php.ini
 - travis_retry composer self-update

install:
 - cd ./projects/tests/
 - rm -f composer.lock
 - rm -rf vendor/
 - composer clearcache
 - composer install

script:
 - ./vendor/bin/phpunit
