inputs:
    set_sources: /home/eric/git/designsecurity/progpilot/package/src/uptodate_data/sources.json
    set_sinks: /home/eric/git/designsecurity/progpilot/package/src/uptodate_data/sinks.json
    set_validators: /home/eric/git/designsecurity/progpilot/package/src/uptodate_data/validators.json
    set_sanitizers: /home/eric/git/designsecurity/progpilot/package/src/uptodate_data/sanitizers.json
    set_include_files: /home/eric/git/designsecurity/progpilot/projects/phar/include_files.json
    set_sources: 
    set_sinks: 
    set_validators: 
    set_sanitizers: 
    set_exclude_files:
    set_folder:
    set_file: /home/eric/git/designsecurity/progpilot/projects/example/example1.php
    set_code:
    set_resolved_includes:
    set_false_positives:
    
outputs:
    tainted_flow: false
    resolve_includes: false
    resolve_includes_file:
    
options:
    set_analyze_js: false
    set_analyze_includes: true
    set_analyze_functions: true
    set_print_file: true
