inputs:
    set_sources: ../uptodate_data/sources.json
    set_sinks: ../uptodate_data/sinks.json
    set_validators: ../uptodate_data/validators.json
    set_sanitizers: ../uptodate_data/sanitizers.json
    set_include_files: 
    set_exclude_files: 
    set_folder: 
    set_file: /home/eric/Téléchargements/DVWA-master/vulnerabilities/xss_r/index.php
    set_code:
    set_resolved_includes:
    set_false_positives:
    
outputs:
    tainted_flow: false
    resolve_includes: false
    resolve_includes_file:
    
options:
    set_analyze_js: false
    set_analyze_includes: true
    set_analyze_functions: true
    set_print_file: true
    set_print_warning: false
    set_limit_time: 10
    set_limit_defs: 10000
