inputs:
    setSources: ../../package/src/uptodate_data/sources.json
    setSinks: ../../package/src/uptodate_data/sinks.json
    setValidators: ../../package/src/uptodate_data/validators.json
    setSanitizers: ../../package/src/uptodate_data/sanitizers.json
    setCustomRules: ../../package/src/uptodate_data/rules.json
    setIncludeFiles: 
    setExcludeFiles: 
    setFolder: /home/eric/dev/scripts/drupal/
    setFile: 
    setCode:
    setResolvedIncludes:
    setFalsePositives:
    
outputs:
    taintedFlow: true
    resolveIncludes: false
    resolveIncludesFile:
    
options:
    setAnalyzeJs: false
    setAnalyzeIncludes: true
    setAnalyzeFunctions: true
    setAnalyzeHardrules: true
    setPrintFile: true
    setPrintWarning: false
    setPrettyPrint: true
    setLimitTime: 10
    setLimitDefs: 3000
    setLimitSize: 500000
